# ***** Network state *****
variable "net_remote_state_region" {
  description = "Region for network remote state"
  type        = string
  nullable    = false
}

variable "net_backet_remote_state" {
  description = "Bucket name for network remote state"
  type        = string
  nullable    = false
}

variable "net_key_remote_state" {
  description = "Key name for network remote state"
  type        = string
  nullable    = false
}

variable "net_vpc_name" {
  description = "VPC name"
  type        = list(string)
  nullable    = false
}

# ***** Target group *****
variable "lb_name" {
  description = "Name of the target group. NULL = generated by Terraform."
  type        = string
  default     = null
}

variable "lb_port" {
  description = "Port on which targets receive traffic"
  type        = number
  nullable    = false
}

variable "lb_protocol" {
  description = "Protocol to use for routing traffic to the targets"
  type        = string
  nullable    = false
  default     = "HTTP"
}
